# Builds the project in multiple modes and runs all of the existing unit tests.

name: "Build-Run-Ubuntu"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

# Note that the container created by workflows maps part of the local volume to
# the container. Specifically ~/actions-runner/_work. Successive jobs can reuse
# the output of their predecessors without having to generate artifacts.
jobs:
  build-release:
    runs-on: [self-hosted, linux]
    container:
      image: ${{vars.BUILD_IMAGE}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: build-ubuntu-workflow
          submodules: true

      - name: Set script as executable
        run: |
          cd build-ubuntu-workflow
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=release ..
          make -j4
          cd ..

  build-debug:
    runs-on: [self-hosted, linux]
    needs: build-release
    container:
      image: ${{vars.BUILD_IMAGE}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: build-ubuntu-workflow
          submodules: true

      - name: Where the hell am I
        run: |
          pwd
          ls -lah

      - name: Build in debug
        run: |
          cd build-ubuntu-workflow
          mkdir build
          cd build
          cmake ..
          make -j4
          cd ..

  find-catch2-tests:
    needs: build-debug
    runs-on: [self-hosted, linux]
    defaults:
      run:
        working-directory: build-ubuntu-workflow
    container:
      image: ${{vars.BUILD_IMAGE}}
    steps:
      - name: Find all catch2 tests in build/exec_tests folder
        id: test_finder
        run: |
          exec_test_names=$( ls build/exec_tests )
          json_test_names=
          for e in ${exec_test_names}; do json_test_names=$json_test_names\"${e}\"\ ;done
          echo "json test names: ${json_test_names}"
          json_test_names=$( echo $json_test_names | tr ' ' ,)
          echo "json test names: ${json_test_names}"
          json_test_names=$( echo [ $json_test_names ] )
          echo "json test names: ${json_test_names}"
          echo "EXEC_TESTS_STR=${json_test_names}" >> $GITHUB_OUTPUT

      - name: Set date string
        id: date_step
        run: |
          date_str=$(TZ='America/New_York' date +"%Y-%m-%d-%H-%M-%S")
          echo "DATE_STR=${date_str}" >> $GITHUB_OUTPUT

    outputs:
      EXEC_TESTS_STR: ${{ steps.test_finder.outputs.EXEC_TESTS_STR }}
      BUILD_DATE_STR: ${{ steps.date_step.outputs.DATE_STR }}

  run-catch2-tests:
    needs: find-catch2-tests
    runs-on: [self-hosted, linux]
    defaults:
      run:
        working-directory: build-ubuntu-workflow
    strategy:
      fail-fast: false
      matrix:
        test_name: ${{fromJson(needs.find-catch2-tests.outputs.EXEC_TESTS_STR)}}
    container:
      image: ${{vars.BUILD_IMAGE}}
    steps:
      - name: Look at the current directory
        run: |
          pwd
          ls -lah
          ls build

      - name: Check if build and tests folders exist
        run: |
          if [ -d build/exec_tests ]; then echo "Test folder found, running tests"; else exit 1; fi

      - name: Run ${{ matrix.test_name }}
        run: |
          cd build
          test_dir=test_output
          mkdir -p $test_dir
          echo Running test: ${{ matrix.test_name }}
          ./exec_tests/${{ matrix.test_name }}

      - name: Move and rename any JSON files from failed test to output folder
        if: failure()
        run: |
          cd build
          test_dir=test_output
          for f in $( ls | grep json )
          do
            echo Moving $f to $test_dir/${{ matrix.test_name }}_$f
            mv $f $test_dir/${{ matrix.test_name }}_$f
          done

      - name: Delete any straggling JSON files
        run: |
          cd build
          for f in $( ls | grep json )
          do
            rm $f
          done

    outputs:
      BUILD_DATE_STR: ${{ needs.find-catch2-tests.outputs.BUILD_DATE_STR }}

  # Need to add secrets :'(
  upload-test-output:
    needs: run-catch2-tests
    runs-on: [self-hosted, linux]
    defaults:
      run:
        working-directory: build-ubuntu-workflow
    container:
      image: ${{vars.BUILD_IMAGE}}
    if: always()
    steps:
      - name: Upload test output to S3
        run: |
          cd build/test_output
          echo "Looking at files $( ls | grep json )"
          date_str=${{ needs.run-catch2-tests.outputs.BUILD_DATE_STR }}
          for f in $( ls | grep json )
          do
            filename=$f
            python3 ../../scripts/upload_artifacts.py ${{secrets.AWS_ACCESS_KEY_ID}} ${{secrets.AWS_SECRET_ACCESS_KEY}} ${{vars.ARTIFACT_BUCKET_NAME}} $filename ${GITHUB_REF_NAME} test-configs ${date_str}
          done
